project_name: browsh
builds:
  - main: .
    binary: browsh
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w
    hooks:
      post: ./contrib/upx_compress_binary.sh

archive:
  format: binary

fpm:
  vendor: Browsh
  homepage: https://brow.sh
  maintainer: Thomas Buckley-Houston <tom@tombh.co.uk>
  description: A fully interactive, realtime and modern browser rendered to TTY
  license: GPL v3
  formats:
    - deb
    - rpm
    - pacman

  dependencies:
    - firefox

release:
  # Obviously need to remove this when we release properly. Hopefully very soon!
  prerelease: true
  draft: true
