[package]
name = "browsh"
version = "0.1.0"
authors = ["Tom Buckley-Houston <tom@tombh.co.uk>"]

[dependencies]
termsize = "0.1.5"
websocket = "0.20.2"

[[bin]]
name = "browsh"
path = "ws-server.rs"

