project_name: browsh
builds:
  - main: .
    binary: browsh
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags: -s -w
    hooks:
      post: ../contrib/upx_compress_binary.sh

archive:
  format_overrides:
    - goos: windows
      format: binary
    - goos: linux
      format: binary
    - goos: freebsd
      format: binary

nfpm:
  vendor: Browsh
  homepage: https://www.brow.sh
  maintainer: Thomas Buckley-Houston <tom@tombh.co.uk>
  description: The modern, text-based browser
  license: GPL v3
  formats:
    - deb
    - rpm

  dependencies:
    - firefox
  overrides:
    deb:
      dependencies:
        'firefox | firefox-esr'

brew:
  name: browsh

  # Repository to push the tap to.
  github:
    owner: browsh-org
    name: homebrew-browsh

  commit_author:
    name: Goreleaser Bot care of Travis CI
    email: builds@travis-ci.com

  homepage: "https://www.brow.sh"

  description: "The modern, text-based browser"

  dependencies:
    - firefox
